import React, { useMemo, useState } from 'react';
import { Download, Plus, Search, Sparkles } from 'lucide-react';

type Status = 'In-Session' | 'Confirmed' | 'Waitlisted';
type Booking = { id: string; time: string; suite: string; guest: string; initials: string; tier: string; property: string; treatment: string; detail: string; therapist: string; status: Status };

const bookings: Booking[] = [
  { id: 'spa-801', time: '09:00 - 10:15 AM', suite: 'Suite 3 (Oceanfront)', guest: 'Sophia Hartwell', initials: 'SH', tier: 'Gold VIP', property: 'Meridian Maldives Beach Resort', treatment: 'Deep Tissue Marine Therapy', detail: '75 min · Organic Algae Oil', therapist: 'Amina Al-Mansoor', status: 'In-Session' },
  { id: 'spa-802', time: '10:30 - 11:45 AM', suite: 'Lotus Pavilion 1', guest: 'Lord Raymond Chen', initials: 'LR', tier: 'Platinum Royal', property: 'Meridian Phuket Ocean Pavilion', treatment: 'Royal Thai Herbal Compress', detail: '75 min · Lemongrass Essence', therapist: 'Somchai Prasert', status: 'Confirmed' },
  { id: 'spa-803', time: '11:00 - 12:30 PM', suite: 'Hydro Lounge A', guest: 'Elena Rostova', initials: 'ER', tier: 'Silver Member', property: 'Meridian Como Villa Retreat', treatment: 'Thermal Mineral Float & Scrub', detail: '90 min · Magnesium Soak', therapist: 'Matteo De Luca', status: 'Confirmed' },
  { id: 'spa-804', time: '01:30 - 02:30 PM', suite: 'Cedar Suite 4', guest: 'Marcus Vance', initials: 'MV', tier: 'Gold VIP', property: 'Meridian Mountain Grand Spa', treatment: 'Alpine Pine Detox Ritual', detail: '60 min · Cedar Extract', therapist: 'Hanna Weber', status: 'Waitlisted' },
  { id: 'spa-805', time: '03:00 - 04:15 PM', suite: 'Oasis Dome 2', guest: 'Fatima Tariq', initials: 'FT', tier: 'Platinum Royal', property: 'Meridian Desert Oasis Spa', treatment: 'Desert Frankincense Warming Wrap', detail: '75 min · Myrrh Infusion', therapist: 'Zaid Noman', status: 'Confirmed' },
  { id: 'spa-806', time: '04:45 - 06:00 PM', suite: 'Bamboo Suite 6', guest: 'Kenji Watanabe', initials: 'KW', tier: 'Standard Guest', property: 'Meridian Bali Sanctuary', treatment: 'Balinese Boreh Herbal Exfoliation', detail: '75 min · Ginger & Clove Warmth', therapist: 'Ni Ketut Ari', status: 'Confirmed' },
  { id: 'spa-807', time: '06:15 - 07:30 PM', suite: 'Garden Room 2', guest: 'Amara Okafor', initials: 'AO', tier: 'Gold VIP', property: 'Meridian Rainforest Sanctuary', treatment: 'Ayurvedic Renewal Ritual', detail: '75 min · Brahmi Oil', therapist: 'Priya Shah', status: 'Confirmed' },
  { id: 'spa-808', time: '07:30 - 08:30 PM', suite: 'Azure Suite 1', guest: 'Daniel Kim', initials: 'DK', tier: 'Standard Guest', property: 'Meridian Azure Cove', treatment: 'Ocean Stone Ritual', detail: '60 min · Volcanic Basalt', therapist: 'Lina Moretti', status: 'Confirmed' },
  { id: 'spa-809', time: '08:00 - 09:30 PM', suite: 'Coral Pavilion', guest: 'Priya Nair', initials: 'PN', tier: 'Silver Member', property: 'Meridian Coral Sands', treatment: 'Tropical Botanical Facial', detail: '90 min · Living Kelp', therapist: 'Sofia Laurent', status: 'Confirmed' },
  { id: 'spa-810', time: '08:30 - 10:00 PM', suite: 'Sunset Villa', guest: 'Noah Kim', initials: 'NK', tier: 'Gold VIP', property: 'Meridian Sunset Cliffs', treatment: 'Couples Sunset Ritual', detail: '90 min · Coconut Milk', therapist: 'Maya Sari', status: 'Waitlisted' },
  { id: 'spa-811', time: '09:00 - 10:15 PM', suite: 'Pearl Suite', guest: 'Ava Thompson', initials: 'AT', tier: 'Platinum Royal', property: 'Meridian Ocean Pearl', treatment: 'Deep Recovery Therapy', detail: '75 min · Arnica Compress', therapist: 'Nalin Perera', status: 'Confirmed' },
  { id: 'spa-812', time: '09:30 - 11:00 PM', suite: 'Palm Garden', guest: 'Oliver Grant', initials: 'OG', tier: 'Standard Guest', property: 'Meridian Palm Bay', treatment: 'Signature Meridian Massage', detail: '90 min · Coconut Oil', therapist: 'Anika Rao', status: 'Confirmed' },
];

const chartData = [['Maldives', 8], ['Phuket', 7], ['Como', 8], ['Mountain', 5], ['Desert', 6], ['Bali', 3]];
const treatmentShare = [['Deep Tissue Marine', 37], ['Royal Thai', 21], ['Hydrotherapy Float', 16], ['Alpine Pine Detox', 13], ['Desert Frankincense', 8], ['Balinese Boreh', 5]];

export default function SpaBookingsExperience() {
  const [property, setProperty] = useState('All Properties (6)');
  const [status, setStatus] = useState<'All Statuses' | Status>('All Statuses');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => bookings.filter((booking) => {
    const query = search.trim().toLowerCase();
    return (status === 'All Statuses' || booking.status === status) && (property === 'All Properties (6)' || booking.property === property) && (!query || `${booking.guest} ${booking.therapist} ${booking.id}`.toLowerCase().includes(query));
  }), [property, search, status]);
  const visible = filtered.slice((page - 1) * 6, page * 6);

  return <section className="spa-operations-page" aria-labelledby="spa-schedule-title">
    <div className="spa-page-heading"><div className="spa-heading-copy"><div className="spa-heading-icon"><Sparkles /></div><div><div className="spa-breadcrumb">Dashboard <span>›</span> Today&apos;s Spa Schedule</div><h2 id="spa-schedule-title">Today&apos;s Spa Schedule</h2><p>A consolidated view of today&apos;s spa bookings across all properties.</p></div></div><div className="spa-heading-actions"><span>Last updated: <strong>09:15 AM</strong><i /></span><button className="spa-primary-button" type="button">↻ &nbsp; Refresh Data</button></div></div>
    <div className="spa-kpi-grid"><Kpi label="Total Spa Bookings" value="12" note="Across all 6 luxury spa pavilions" badge="+15%" /><Kpi label="Room Utilization" value="82%" note="28 of 34 treatment suites active" badge="Peak: 2-5 PM" /><Kpi label="Slots Available Today" value="9" note="Available across all properties" badge="Limited" warning /></div>
    <div className="spa-chart-grid"><div className="spa-chart-panel"><div className="spa-panel-heading"><h3>Appointments by Property</h3><span>▮ Bookings Today　|　Target: 6 avg</span></div><div className="spa-bars">{chartData.map(([label, value]) => <div className="spa-bar-item" key={label}><b>{value}</b><i style={{ height: `${value * 10}%` }} /><span>{label}</span></div>)}</div><footer>Real-time booking distribution across all 6 resort destinations.<strong>Updated 09:15 AM</strong></footer></div><div className="spa-chart-panel"><div className="spa-panel-heading"><h3>Share of Today&apos;s Treatments</h3><span className="spa-total-pill">38 Total</span></div><div className="spa-donut"><strong>38<small>TREATMENTS</small></strong></div><div className="spa-legend">{treatmentShare.map(([label, value], index) => <span key={label}><i className={`legend-${index}`} />{label}<b>{value}%</b></span>)}</div><footer>All 6 signature rituals aligned with seasonal solstice therapy.</footer></div></div>
    <div className="spa-table-panel"><div className="spa-table-heading"><h3>✦ Spa Schedule Details ({filtered.length})</h3><div><button className="spa-primary-button" type="button"><Plus size={15} /> Book Appointment</button><button className="spa-export-button" type="button"><Download size={15} /> Export</button></div></div><div className="spa-filters"><label>Property<select value={property} onChange={(event) => { setProperty(event.target.value); setPage(1); }}><option>All Properties (6)</option>{[...new Set(bookings.map((booking) => booking.property))].map((name) => <option key={name}>{name}</option>)}</select></label><div className="spa-status-filters">{(['All Statuses', 'In-Session', 'Confirmed', 'Waitlisted'] as const).map((item) => <button key={item} className={status === item ? 'active' : ''} type="button" onClick={() => { setStatus(item); setPage(1); }}>{item}</button>)}</div><div className="spa-search"><Search size={17} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search by guest name, therapist, or booking ID..." /></div></div><div className="spa-table-scroll"><table><thead><tr>{['Booking ID', 'Time & Suite', 'Guest Name', 'Property', 'Treatment', 'Therapist', 'Status', 'Actions'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{visible.map((booking) => <tr key={booking.id}><td className="spa-id">{booking.id}</td><td><strong>{booking.time}</strong><small>{booking.suite}</small></td><td><div className="spa-guest"><i>{booking.initials}</i><span><strong>{booking.guest}</strong><small>✦ {booking.tier}</small></span></div></td><td>{booking.property}</td><td><strong>{booking.treatment}</strong><small>{booking.detail}</small></td><td>{booking.therapist}</td><td><span className={`spa-status ${booking.status.toLowerCase().replace('-', '')}`}><i />{booking.status}</span></td><td><button className="spa-view-button" type="button">{booking.status === 'Waitlisted' ? 'Manage' : 'View'}</button></td></tr>)}</tbody></table></div><div className="spa-pagination"><span>Showing <strong>{filtered.length ? (page - 1) * 6 + 1 : 0} to {Math.min(page * 6, filtered.length)}</strong> of {filtered.length} appointments</span><div><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><strong>{page}</strong><button type="button" disabled={page * 6 >= filtered.length} onClick={() => setPage(page + 1)}>Next</button></div></div></div>
  </section>;
}

function Kpi({ label, value, note, badge, warning = false }: { label: string; value: string; note: string; badge: string; warning?: boolean }) {
  return <div className="spa-kpi-card"><div><span>{label}</span><em className={warning ? 'warning' : ''}>{badge}</em></div><strong>{value}</strong><small>{note}</small></div>;
}
